<?xml version="1.0" encoding="utf-8"?>
<Database Name="ASPNETDB" Class="DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=C:\Users\negonicrac\Development\seniorproject2009\DV_Enterprises.Web\DV_Enterprises.Website\App_Data\ASPNETDB.MDF;Integrated Security=True;User Instance=True" SettingsObjectName="DV_Enterprises.Web.Properties.Settings" SettingsPropertyName="ASPNETDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Users" Member="Users">
    <Type Name="User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Section" Member="Sections" ThisKey="UserId" OtherKey="UserId" Type="Section" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Section" Member="Sections">
    <Type Name="Section">
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GreenhouseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnviromentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CropId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="User_Section" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Greenhouse_Section" Member="Greenhouse" ThisKey="GreenhouseId" OtherKey="GreenhouseId" Type="Greenhouse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Greenhouse" Member="Greenhouses">
    <Type Name="Greenhouse">
      <Column Name="GreenhouseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Greenhouse_Section" Member="Sections" ThisKey="GreenhouseId" OtherKey="GreenhouseId" Type="Section" />
      <Association Name="dvent_Location_Greenhouse" Member="Location" ThisKey="LocationId" OtherKey="LocationId" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_ProductImage" Member="Images">
    <Type Name="Image">
      <Column Name="ProductImageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Image" Member="Product" ThisKey="ProductId" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Product_Image" Member="Images" ThisKey="ProductID" OtherKey="ProductId" Type="Image" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Location" Member="Locations">
    <Type Name="Location">
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="dvent_Location_Greenhouse" Member="Greenhouses" ThisKey="LocationId" OtherKey="LocationId" Type="Greenhouse" />
    </Type>
  </Table>
</Database>