<?xml version="1.0" encoding="utf-8"?>
<Database Name="ASPNETDB" EntityNamespace="DV_Enterprises.Web.BLL" ContextNamespace="DV_Enterprises.Web.DAL" Class="DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=C:\Users\negonicrac\Development\seniorproject2009\DV_Enterprises.Web\DV_Enterprises.Website\App_Data\ASPNETDB.MDF;Integrated Security=True;User Instance=True" SettingsObjectName="DV_Enterprises.Web.Properties.Settings" SettingsPropertyName="ASPNETDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dvent_Crop" Member="Crops">
    <Type Name="Crop">
      <Column Name="CropId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinTemperature" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxTemperature" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MinHumidity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxHumidity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="dvent_Crop_dvent_Environment" Member="Environments" OtherKey="CropId" Type="Environment" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_SectionLog" Member="SectionLogs">
    <Type Name="SectionLog">
      <Column Name="SectionLogId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Time" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Temperature" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Humidity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isLightOn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="dvent_Section_dvent_SectionLog" Member="Section" ThisKey="SectionId" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Environment" Member="Environments">
    <Type Name="Environment">
      <Column Name="EnvironmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CropId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxTemp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinTemp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxHumidity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinHumidity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="dvent_Environment_dvent_Schedule" Member="Schedules" OtherKey="EnviromentId" Type="Schedule" />
      <Association Name="dvent_Environment_dvent_Section" Member="Sections" OtherKey="EnviromentId" Type="Section" />
      <Association Name="dvent_Crop_dvent_Environment" Member="Crop" ThisKey="CropId" Type="Crop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Greenhouse" Member="Greenhouses">
    <Type Name="Greenhouse">
      <Column Name="GreenhouseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="dvent_Greenhouse_dvent_Section" Member="Sections" OtherKey="GreenhouseId" Type="Section" />
      <Association Name="dvent_Location_dvent_Greenhouse" Member="Location" ThisKey="LocationId" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Location" Member="Locations">
    <Type Name="Location">
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="dvent_Location_dvent_Greenhouse" Member="Greenhouses" OtherKey="LocationId" Type="Greenhouse" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="ScheduleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="interval" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnviromentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="dvent_Environment_dvent_Schedule" Member="Environment" ThisKey="EnviromentId" Type="Environment" IsForeignKey="true" />
      <Association Name="dvent_ScheduleType_dvent_Schedule" Member="ScheduleType" ThisKey="ScheduleTypeId" Type="ScheduleType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_ScheduleType" Member="ScheduleTypes">
    <Type Name="ScheduleType">
      <Column Name="ScheduleTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(253) NOT NULL" CanBeNull="false" />
      <Association Name="dvent_ScheduleType_dvent_Schedule" Member="Schedules" OtherKey="ScheduleTypeId" Type="Schedule" />
    </Type>
  </Table>
  <Table Name="dbo.dvent_Section" Member="Sections">
    <Type Name="Section">
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GreenhouseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnviromentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CropId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="OwnerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="dvent_Section_dvent_SectionLog" Member="SectionLogs" OtherKey="SectionId" Type="SectionLog" />
      <Association Name="dvent_Environment_dvent_Section" Member="Environment" ThisKey="EnviromentId" Type="Environment" IsForeignKey="true" />
      <Association Name="dvent_Greenhouse_dvent_Section" Member="Greenhouse" ThisKey="GreenhouseId" Type="Greenhouse" IsForeignKey="true" />
    </Type>
  </Table>
</Database>