<%@ Page Title="Terms of Use &mdash; Smart GreenHouse Solutions" Language="C#" MasterPageFile="~/Template.master" AutoEventWireup="true" CodeFile="TermsOfUse.aspx.cs" Inherits="Legal_TermsOfUse" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<h2 class="title">Terms of Use</h2>
<h3 class="title">Terms and Conditions</h3>
<p>DV Enterprise owns all materials on this Website ("Site"); including all information, documents, communications, files, text, graphics, software, and products (collectively "Materials"). All materials available for use are subject to the terms and conditions set forth in this document. DV Enterprise reserves all rights to make changes to these Terms and Conditions at any time. By downloading, installing, or using any Materials, you agree to these Terms and Conditions. If you do not agree to these Terms and Conditions, you may not use, access, download, or install any Materials located within our Site.</p>
<p>For those Materials made available for download from this Site which are accompanied by or include an end user License Agreement; the License Agreement will prevail over these Terms and Conditions. Certain third party Materials made available for download from this Site will be accompanied and governed by License Agreements between you and a third party ("Third Party Agreements"). DV Enterprise is not a party to such Third Party Agreements and DV Enterprise’s liability to you and to third parties is limited to the warranty disclaimers and limitation of liability in these Terms and Conditions. You agree not to install, access, use, or download the Materials unless you have read and agree with the terms of the applicable license agreement.</p>
<p>DV Enterprise authorizes you to use a single copy of the Materials solely for non-commercial personal use, provided that you retain all copyright and other proprietary notices contained in the original and any copies of the Materials obtained.</p>
<p>Certain codes found in the Materials are specifically referenced as a sample software code ("Sample Code"). If such Sample Code is accompanied by a License Agreement, then the terms of the License Agreement shall govern. If a License Agreement does not accompany or is not included with the Sample Code then such Sample Code shall be governed by these Terms and Condition. You may copy, perform, display, distribute, create derivative works, modify, and sublicense through multiple channels such Sample Code (in whole or in part). Under no circumstances will content include images, ringtones, or graphics as a Sample Code.</p>
<h3 class="title">Ownership; Restrictions</h3>
<p>The copyright and ownership interests in all Materials is held by DV Enterprise and its suppliers and protected by U.S. laws and international treaty provisions. You agree not to use, copy, republish, frame, post, transfer, display, perform, download, transmit, modify, rent, lease, loan, sell, assign, distribute, license, sublicense, reverse engineer, or create derivative works based on the Materials, except as expressly allowed in this document. Unauthorized use of any Materials will violate copyright laws, trademark laws, the laws of privacy and publicity, communications regulations and statutes or other applicable laws, rules or regulations, and may subject you to civil liability and/or criminal penalties. Violators will be subject to fines, imprisonment or both.</p>
<p>These Terms and Conditions are effective until terminated by DV Enterprise. DV Enterprise may terminate these Terms and Conditions without notice at any time for any reason. Upon termination all rights granted in these Terms and Conditions shall immediately cease to exist and you must promptly discontinue all use of the Materials and this Site and destroy all copies of the Materials downloaded by you. In addition, in the event that we determine, in our sole discretion, that you have breached any of our Terms and Conditions, we reserve the right to terminate access to this Site and take any other action; which we, in our sole discretion, deem to be appropriate.</p>
<h3 class="title">Disclaimer</h3>
<p>You acknowledge and agree that the Materials provided to you are on an "as is" basis, without any warranty of any kind. All warranties express or implied cover Materials or any services related to the Materials are expressly disclaimed to the fullest extent permitted by law.</p>
<p>No warranty or representation is given that the functions contained in the Materials will meet your requirements, operate uninterrupted or error-free, or that any defects in the Materials be corrected. Furthermore, no warranty or representation is given regarding the use or the results of the use of the Material or the adequacy of the Materials. No oral or written information or advice given by any person or entity shall create a warranty or representation or in any way increase the scope of this warranty. Some states or jurisdictions do not allow the exclusion of implied warranties or limitations on how long an implied warranty may last, so the above limitations may not apply to you.</p>
<h3 class="title">Trademarks</h3>
<p>The trademarks, service marks and logos used and displayed in the Materials are registered and unregistered trademarks and service marks of DV Enterprise and others. All other registered and unregistered trademarks used in the Materials are the property of their respective owners. You are not granted, expressly or by implication, estoppels or otherwise, any license or right to use any DV Enterprise trademark, service mark or logo used or displayed in the Materials without the prior express written permission of DV Enterprise. When used with DV Enterprise’s permission, all trademarks must be identified as trademarks of DV Enterprise using the appropriate symbol (e.g., ™ or ®) at the first occurrence in the text of any published printed or electronic communications, including advertising, promotions, packaging, technical documentation, sales and marketing collateral and product labels. In addition, such marks must be listed, identified and attributed as the property of DV Enterprise in a footnote at the end of the communication.</p>
<h3 class="title">Patents</h3> 
<p>DV Enterprise technology may be protected by one or more United States and/or international patents or patents pending.</p>
<h3 class="title">Personal Information </h3>
<p>Information submitted to DV Enterprise through the Site is governed by DV Enterprise Privacy Policy.</p>
<h3 class="title">User Submissions</h3>
<p>Except as provided in the Privacy Policy, no ideas, material, computer code, information or other communication you submit or post to the Site will be considered confidential or proprietary. All such material becomes the exclusive property of DV Enterprise, which is entitled to use such material for any purpose without restriction or compensation. You are prohibited from posting or transmitting to or from the Site any unlawful, infringing, threatening, libelous, defamatory, obscene or pornographic material or any other material that would violate any law.</p>
<h3 class="title">LIMITATION OF LIABILITY</h3>
<P>UNDER NO EVENT AND UNDER NO LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, SHALL OPENWAVE OR ITS SUPPLIERS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTIAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND; INCLUDING, WITHOUT LIMITATION, DAMAGES FOR ANY LOST PROFITS, LOST SAVINGS, LOSS OF DATA, COSTS, FEES OR EXPENSES OF ANY KIND OR NATURE ARISING OUT OF OR RELATING TO THESE TERMS AND CONDITIONS, THIS SITE, OR THE USE OR INABILITY TO USE THE MATERIALS, OR ANY DATA SUPPLIED THEREWITH, EVEN IF OPENWAVE OR AN OPENWAVE REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. Some jurisdictions do not allow the exclusion or limitation of incidental, consequential or special damages, so the above limitation or exclusion may not apply to you.</P>
<h3 class="title">Contact Information</h3>
<p>All requests for further information or for permission to reproduce any portions of the Materials should be directed to: DV Enterprise, 4000 Millenia Blvd Orlando, Florida 32839 [Tel]: 888-857-5757 [Fax]: 407-859-6000.</p>
</asp:Content>

